version: '2'
services:
    dataload-app:
        image: dataload
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dataload-mysql:3306/dataload?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dataload-mysql:
        extends:
            file: mysql.yml
            service: dataload-mysql
